gluster/gluster-kubernetes

- README.md
> Some readme content.

- README.md
> Update readme -- more content.

- config/deploy-heketi-deployment.json
- config/glusterfs-deployment.json
- config/heketi-deployment.json
- config/heketi-service-account.yaml
> config: Add artifacts to deploy.

- docs/setup-guide.md
> docs: add first content into setup-guide

- docs/setup-guide.md
> setup-guide: rework the instructions slightly

- README.md
> Highlight the demo link some more

- README.md
> readme: improve sectioning

- docs/index.md
> remove last remnant of working name

- README.md
> Fix rebase artifacts.

- deploy/templates/deploy-heketi-deployment.json
- deploy/templates/glusterfs-deployment.json
> Docker images: Deployment configs should point to supported docker images

- deploy/gk-deploy
Fix command-line option parsing and add namespace option.
Closes #26 
Closes #27
> Options updates

- deploy/gk-deploy
Noticed a few things to clean up, including waiting for service account secrets to populate.
> Minor fixes to scripting

- README.md
> Further clarify topology file usage.

- README.md
> README: fix gk-heketi -> gk-deploy

- docs/setup-guide.md
> Fix a few typo in the documentation

- README.md
- docs/examples/hello_world/README.md
- docs/examples/hello_world/gluster-pvc.yaml
- docs/examples/hello_world/gluster-storage-class.yaml
- docs/examples/hello_world/nginx-pod.yaml
Fixes #42 
Adding correct yaml for this version of vagrant quickstart and an examples section including a HelloWorld to finish the quickstart thought
> adding helloworld example to finish out quickstart

- README.md
fix broken links on previous PR
@jarrpa -  ooops!  I had a typo in the link
> fix broken links on README.md

- vagrant/roles/common/tasks/main.yml
- vagrant/roles/nodes/tasks/main.yml
Some small ansible updates I've put in as a workaround for being on a slow Internet connection. The documentation updates are inspired by and supersede those in #40.
> Small ansible updates

- deploy/gk-deploy
> CLI:Namespace added

- deploy/gk-deploy
> Namespace:user add to given namespace

- README.md
- docs/setup-guide.md
Major updates to the README and setup-guide.
> Major documentation update

- vagrant/roles/common/tasks/main.yml
revert of #61 - @jarrpa PTAL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/72)
> revert of #61

- deploy/gk-deploy
Closes: #75 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/78)
> Check for TOPOLOGY file before start execution

- deploy/gk-deploy
closes : #54 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/77)
> Handling stderr and stdout fo check_pods()

- vagrant/roles/common/tasks/main.yml
- vagrant/roles/nodes/tasks/main.yml
per conversation in #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/73)
> adding some retry logic for network intensive tasks

- deploy/ocp-templates/glusterfs-template.yaml
closes : #83 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/89)
> Glusterfs Template:Read only boolean value added as string

- deploy/gk-deploy
Closes: #95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/96)
> append to log file instead of overwriting

- deploy/gk-deploy
closes: #84 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/82)
> Gluster templates are added without -g

- deploy/ocp-templates/deploy-heketi-template.yaml
- deploy/ocp-templates/heketi-template.yaml
Closes: #109 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/110)
> Heketi yaml templates fix

- deploy/gk-deploy
Closes: #55 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/81)
> Storagenode label remove on ABORT

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/111)
> Silence extraneous curl output

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/115)
> Remove router comment from Kubernetes deployment.

- deploy/gk-deploy
Closes: #50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/119)
> Use current namespace instead of default

- deploy/gk-deploy
Closes: #104 
Pair Programmed with: Ramakrishna Reddy Yekulla <rreddy@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/121)
> gk-deploy: Error and Exit when heketi-cli commands failed

- deploy/gk-deploy
Closes: #105 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/122)
> gk-deploy to resume from Heketi topology load resume

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/123)
> Indent error

- deploy/kube-templates/heketi-deployment.yaml
- deploy/ocp-templates/deploy-heketi-template.yaml
- deploy/ocp-templates/heketi-template.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/124)
> Indent and Missing parameters in templates

- deploy/gk-deploy
> Namespace to check exact namespace

- deploy/sample-gluster-endpoints.yaml
- deploy/sample-gluster-service.yaml
> Sample Yaml Service and Endpoint

- deploy/gk-deploy
Make sure we get confirmation from admin/user before proceeding with abort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/132)
> Include a warning message when abort is initiated

- deploy/gk-deploy
Closes: #126 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/134)
> Namespace to error if any similar name with -

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/135)
> Namespace and cli doesn't work with =

- deploy/gk-deploy
Closes: #136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/137)
> use correct label to identify heketi resources

- deploy/ocp-templates/deploy-heketi-template.yaml
- deploy/ocp-templates/glusterfs-template.yaml
- deploy/ocp-templates/heketi-template.yaml
Closes: #143 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/144)
> Strategy added to the spec of dc

- deploy/ocp-templates/deploy-heketi-template.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/146)
> Replace is not a Strategy so changing to Recreate

- deploy/gk-deploy
Signed-off-by: Ramakrishna Reddy Yekulla <rreddy@redhat.com>
Pair Programmed with : Raghavendra Talur <rtalur@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/147)
> abort case should have default case and work accordingly

- docs/examples/hello_world/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/150)
> Copyedit and format recent changes to hello_world's README.

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/151)
> Allow -y to skip --abort prompt.

- deploy/kube-templates/deploy-heketi-deployment.yaml
- deploy/kube-templates/glusterfs-daemonset.yaml
- deploy/kube-templates/heketi-deployment.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/153)
> Update imagePullPolicy in kube-template files to IfNotPresent.

- docs/examples/dynamic_provisioning_external_gluster/README.md
example doc for external glusterfs (non-containerized)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/158)
> adding external gluster example

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/175)
> check existing setup before deployment

- deploy/kube-templates/heketi-deployment.yaml
- deploy/ocp-templates/heketi-template.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/191)
> Have heketi service select pods using the right label.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/196)
> Minor documentation typo fix.

- deploy/ocp-templates/heketi-template.yaml
Fixes #197.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/199)
> Fix selector in heketi OCP template.

- README.md
Fixes #202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/203)
> Remove suggestion of setting KUBECONFIG from the Quickstart guide

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/204)
> Add the serviceAccount to privileged scc

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/206)
> Abort should not be called on heketi failure

- vagrant/demo/README.md
- vagrant/demo/demo-deploy.sh
- vagrant/demo/demo-dynamic-provisioning.sh
- vagrant/demo/demo-inside-deploy.sh
- vagrant/demo/demo-inside-dynamic-provisioning.sh
- vagrant/demo/demo-inside-prepare.sh
- vagrant/demo/demo-inside-status.sh
- vagrant/demo/demo-inside-test-heketi.sh
- vagrant/demo/demo-inside-wrapper.sh
- vagrant/demo/demo-prepare.sh
- vagrant/demo/demo-status.sh
- vagrant/demo/demo-test-heketi.sh
- vagrant/demo/util.sh
These are the demos I created for and presented (in recorded form) at vault 2017.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/210)
> Add Demos for gk-deploy and dynamic provisioning to the vagrant environment

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/205)
> Add Heketi admin and user secret configurable

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/208)
> Should not proceed if endpoint is none for heketi service

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/212)
> Syntax error in script due to #208 PR

- .travis.yml
- deploy/gk-deploy
- tests/README.md
- tests/gk-deploy/test_gk_deploy_basic.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/213)
> tests: test gk-deploy syntax

- vagrant/demo/demo-deploy.sh
- vagrant/demo/demo-dynamic-provisioning.sh
- vagrant/demo/demo-inside-wrapper.sh
- vagrant/demo/demo-prepare.sh
- vagrant/demo/demo-status.sh
- vagrant/demo/demo-test-heketi.sh
Only set those variables really needed in the scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/217)
> vagrant:demo: clean up variables a bit

- .gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/218)
> add vim backup files to gitignore

- deploy/gk-deploy
Otherwise abort() will give no clues in the log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/221)
> Log command outputs in the abort function

- deploy/gk-deploy
Closes: #219
Signed-off-by: Ramakrishna Reddy Yekulla <rreddy@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/223)
> gk-deploy: Abort if "${CLI} label nodes" command fails

- deploy/gk-deploy
Resolves: #229.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/230)
> gk-deploy: simplify determining heketi address in oc deployment

- docs/examples/containerized_heketi_dedicated_gluster/README.md
- docs/examples/containerized_heketi_dedicated_gluster/heketi-deployment.yaml
- docs/examples/containerized_heketi_dedicated_gluster/heketi.json
This is a simple single node Kube cluster example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/207)
> Adding a simple containerized heketi and dedicated gluster example

- vagrant/ansible-step
optionally provide a task to start at
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/237)
> vagrant: add little helper script to step through ansible

- vagrant/global_vars.yml
- vagrant/roles/common/files/10-kubeadm.conf
- vagrant/roles/common/files/kubernetes.repo
- vagrant/roles/common/tasks/main.yml
- vagrant/roles/master/tasks/main.yml
- vagrant/roles/nodes/tasks/main.yml
--api-advertise-addresses --> --apiserver-advertise-address
https://github.com/kubernetes/kubernetes/pull/42064
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/227)
> vagrant: update to 1.6.1 with a lot of fixes

- deploy/gk-deploy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/239)
> Print Heketi URL in gk-deploy

- deploy/gk-deploy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/240)
> Minor doc fixes

- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/243)
> travis: install realpath in the environment so the tests can run again

- deploy/gk-deploy
Found a couple of smaller issues in gk-deploy.
The failure to error out when the copy-job fails rendered my setup invalid even though it was seemingly successful...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/241)
> some gk-deploy fixes

- vagrant/ansible-step
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/248)
> vagrant: fix quoting problem in ansible-step

- vagrant/roles/nodes/tasks/main.yml
- vagrant/site.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/247)
> wait for nodes to get to Ready state after joining

- deploy/kube-templates/glusterfs-daemonset.yaml
- deploy/ocp-templates/glusterfs-template.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/252)
> Tuning the Liveness and Readiness Probe options to support better scaling of gluster volume

- deploy/gk-deploy
- deploy/ocp-templates/glusterfs-template.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/255)
> Make the node label for gluster pods configurable

- deploy/gk-deploy
this tiny change adds support for non ascii characters in path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/263)
> non ASCII path for topology file

- docs/design/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/267)
> docs: Add a design directory for future purposes.

- deploy/gk-deploy
Resolves #259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/261)
> Greater precision when determining oc version

- deploy/gk-deploy
Related: #234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/271)
> gk-deploy: Update prereqs with SELinux note.

- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/docker_cache.yml
- vagrant/docker_gen_cache.sh
- vagrant/roles/common/tasks/main.yml
- vagrant/roles/master/tasks/main.yml
- vagrant/roles/master/tasks/yum_cache.yml
- vagrant/site.yml
A collection of minor fixes and major hacks I've come up with over time while using the vagrant environment for development, cleaned up for general public consumption. The latter commits can be moved to their own PRs if requested, but I figured I'd start simple. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/273)
> Various vagrant updates

- docs/examples/gluster-s3-storage-template/README.md
- docs/examples/gluster-s3-storage-template/gluster-s3-storageclass.yaml
- docs/examples/gluster-s3-storage-template/gluster-s3-template.yaml
Add a template file for gluster-s3 container.
Add corresponding README having worflow and testing instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/277)
> Template file for gluster-s3 container

- docs/examples/gluster-s3-storage-template/gluster-s3-storageclass.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/278)
> Use the Heketi route url created instead of the IP address

- docs/examples/gluster-s3-storage-template/README.md
- docs/examples/gluster-s3-storage-template/gluster-s3-template.yaml
Add DeploymentConfig with replica for gluster-s3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/283)
> Add DeploymentConfig with replica for gluster-s3.

- docs/setup-guide.md
Fixes #290
Signed-off-by: dougbtv <dosmith@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/291)
> Adds note about having mount.glusterfs available when using gk-deploy with -g option

- docs/examples/gluster-s3-storage-template/README.md
- docs/examples/gluster-s3-storage-template/gluster-s3-template.yaml
GLUSTER_VOLUMES -> S3_ACCOUNT
GLUSTER_USER -> S3_USER
GLUSTER_PASSWORD -> S3_PASSWORD
Update README as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/293)
> Rename few variables as S3 template

- README.md
Based on a recent conversation with @wattsteve .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/294)
> README: Remove "hyper-converged", update messaging

- docs/examples/gluster-s3-storage-template/README.md
Dependency package for s3curl - updated README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/296)
> Dependency package for s3curl - updated README

- README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/295)
> README: Clarify setup at beginning of Quickstart

- tests/complex/test-inside-dynamic-provisioning.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/288)
> tests: cut off infinite loop

- deploy/gk-deploy
- deploy/heketi.json.template
Missed a key configuration parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/297)
> gk-deploy: fix heketi.json for heketi-HA

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/300)
> gk-deploy: mention required kernel modules

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/301)
> gk-deploy: document helper functions

- vagrant/roles/common/tasks/main.yml
- vagrant/roles/master/tasks/main.yml
- vagrant/roles/nodes/tasks/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/303)
> Fix starting the vagrant environment on  Fedora 26

- docs/examples/hello_world/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/306)
> Removed extra space in storage class yaml example

- docs/setup-guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/308)
> fixed typo

- README.md
Update contact info. in README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/309)
> Update contact info. in README

- deploy/gk-deploy
- vagrant/roles/nodes/tasks/main.yml
Signed-off-by: Vijay Bellur <vbellur@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/312)
> Correct description of ports used by Gluster

- docs/examples/gluster-s3-storage-template/gluster-s3-template.yaml
Add liveness, readiness probe for s3 pod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/313)
> Add liveness, readiness probe for s3 pod

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/315)
> gk-deploy: make it possible to run gk-deploy from a different directory

- .gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/316)
> gitignore heketi.json (which is generated)

- tests/complex/test-inside-gk-deploy.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/318)
> tests: Fix conflict resolution error

- docs/examples/hello_world/README.md
Fixes #292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/322)
> Updates Hello World docs to note svc DNS & endpoints parameter

- deploy/heketi.json.template
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/326)
> gk-deploy: Set rebalance_on_expansion true for heketi

- docs/examples/gluster-s3-storage-template/gluster-s3-template.yaml
Remove privileged scc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/331)
> Remove privileged scc

- deploy/gk-deploy
- deploy/kube-templates/gluster-s3-pvcs.yaml
- deploy/kube-templates/gluster-s3-storageclass.yaml
- deploy/kube-templates/gluster-s3-template.yaml
- deploy/ocp-templates/gluster-s3-pvcs.yaml
- deploy/ocp-templates/gluster-s3-storageclass.yaml
- deploy/ocp-templates/gluster-s3-template.yaml
- tests/complex/README.md
- tests/complex/run-all.sh
- tests/complex/run-basic.sh
- tests/complex/run-object.sh
- tests/complex/test-gk-deploy-object.sh
- tests/complex/test-gk-deploy.sh
- tests/complex/test-inside-gk-deploy.sh
- tests/complex/test-inside-object-store-setup.sh
- tests/complex/test-inside-object-store.sh
- tests/complex/test-object-store.sh
- vagrant/roles/master/tasks/main.yml
Depends on: #289, #305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/299)
> gk-deploy: Deploy gluster-s3 container

- deploy/ocp-templates/heketi-template.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/338)
> fix typo for executor type

- deploy/gk-deploy
require if label already exists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/339)
> add --overwrite for nodes

- deploy/kube-templates/glusterfs-daemonset.yaml
- deploy/ocp-templates/glusterfs-template.yaml
Update tcmu-runner's log directory using env. variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/337)
> Update tcmu-runner's log directory using env. variable

- docs/setup-guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/348)
> Fixed minor typo

- deploy/kube-templates/glusterfs-daemonset.yaml
Fix default value for GB_GLFS_LRU_COUNT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/346)
> Fix default value for GB_GLFS_LRU_COUNT

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/353)
> provide flags before env var

- docs/design/gluster-block-provisioning.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/268)
> Design: Gluster-Block Provisioning End-To-End Design

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/354)
> fstab var contains /, hence use # delimiter

- deploy/gk-deploy
#354 fixed this issue in one place, there are two others.
fixes #358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/361)
> / as a sed seperator for filenames causes issues

- deploy/gk-deploy
Check json format of topology.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/364)
> Check json format of topology.json

- MAINTAINERS.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/372)
> Add a MAINTAINERS file.

- docs/examples/hello_world/README.md
Minor doc improvements for the hello world README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/375)
> Minor doc improvements

- docs/design/tls-security.md
Design doc for issue #370
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/382)
> Add design doc for enabling TLS by default

- deploy/gk-deploy
Fixes #390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/391)
> gk-deploy: Fix regression from PR #389

- Makefile
- tests/Makefile
- tests/simple/Makefile
- tests/simple/gk-deploy/Makefile
- tests/simple/shell/Makefile
- tests/simple/yaml/Makefile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/399)
> Makefiles: make all test targets .PHONY

- tests/complex/run-all.sh
- tests/complex/run.sh
I have some more in the making, but sending out these first, since they are ready and self-contained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/401)
> a few improvements on complex test runner scripts

- Makefile
- tests/complex/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/400)
> add a make target for complex tests

- vagrant/roles/nodes/tasks/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/415)
> vagrant: Update kubeadm join command

- deploy/gk-deploy
https://github.com/gluster/gluster-kubernetes/issues/429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/430)
> Fixed issue #429

- deploy/gk-deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/436)
> gk-deploy: redirect command usage to dev null

- README.md
Don't use both bold and italics, but just one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/449)
> README: improve formatting

- README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/530)
> README: replace centos ci build status badge by travis one
