vagrant/roles/common/tasks/main.yml

fixes #60 (at least on RHEL and if it still is flakey, the addition of this is not harmful)
I was able to reproduce this issue pretty regularly by removing the deletion of cache and 'yum clean all' after 'yum install' of epel repo
Not saying this will completely fix this issue, but it seems to have done the trick on my setup and like stated, it won't hurt to have those 2 commands enabled in the tasks.
My Set up is RHEL 7.2 using VirtualBox 5.0 as my provider.

seems to fix some repomd.xml metalink issues on rhel

---

deploy/kube-templates/glusterfs-daemonset.json
deploy/ocp-templates/deploy-heketi-template.json
deploy/ocp-templates/glusterfs-template.json

Update the kube and ocp tempaltes files for GlusterFS to fix a bug
where some Gluster information wasn't being persisted. Also add a
missing argument to the heketi kube template file.

Update template files from heketi project.

---

vagrant/roles/nodes/tasks/main.yml

The iptables rules set in the nodes playbook did not persist across VM reboots. Using firewalld instead.

vagrant: Make firewall changes permanent on nodes

---

deploy/ocp-templates/glusterfs-template.json

If there are more volumes, it may take some time for the gluster containers to come up.  Increasing the probe value considering we are a storage container.

Increase the probe value to 100s

---

deploy/gk-deploy

This closes the #97 and changes have been in the documentation to handle the developer intended behaviour of the script to use a `--log-file ` option instead of the` --log` option
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/98)

Changing logging option in help section

---

vagrant/roles/common/tasks/main.yml

This ensures that all rules are applied for current runtime and also
permanently. Hence, removed the redundant reload firewalld operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/99)

Add immediate flag to all firewalld cmds

---

deploy/gk-deploy

Using the setbuiltin to handle command line execution errors and also handle the unset variables in the  deploy script 
Pair Programmed with @raghavendra-talur
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/113)

set builtin for handling heketi-cli failures

---

deploy/gk-deploy

- Handling it with a error message. The actual router check is being moved to a  prerequisite check  in the deploy script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/114)

Error message to handle router failure

---

deploy/gk-deploy

In an effort to clarify command-line documentation, introduce a
(relatively) short blurb describing the pre-requisites for running
the deployment script. Also add a flag that allows users to skip
it. :)
Closes: #56 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/116)

Print list of pre-requisites, prompt to continue

---

deploy/gk-deploy

Unfortunately this patch proved to be too strict for our requirements.
We will add selective error handling in subsequent patches.
This reverts commit 2426eaf2572717e1a972d4cf420d86a243ccb799.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/118)

Revert "set builtin for handling heketi-cli failures"

---

deploy/gk-deploy

This fixes the abort behaviour, which was prompting for the pre requisite checks to run.

Initiating abort should skip prerequisite checks

---

deploy/gk-deploy
deploy/kube-templates/deploy-heketi-deployment.yaml
deploy/kube-templates/heketi-deployment.yaml
deploy/ocp-templates/deploy-heketi-template.yaml
deploy/ocp-templates/heketi-template.yaml

The PR https://github.com/heketi/heketi/pull/622 has caused a need to update our deployment. As heketi now uses the heketi-service-account Service Account by default and grabs all its environmental context from that, we no longer have to provide namespace, kubeapi, or even the Service Account secret.
A side-effect of this is that the OpenShift deployment now seems to require that heketi-service-account be priviledged, that is we seem to need:
```
oadm add-scc-to-user privileged system:serviceaccount:<project namespace>:heketi-service-account
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/112)

Updates for heketi autoconfig

---

deploy/gk-deploy

Updated globs for checking CLI tool to not missfire on paths containing 'oc'
Issue raised in: https://github.com/gluster/gluster-kubernetes/issues/145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/148)

Updated gk-deploy to fix CLI select globs

---

README.md

Updated documentation to fetch the heketi service IP and port instead of the service's endpoint IP and port.  When users follow the docs (base README and hello world README), they set up a storage class that is set up to talk to the heketi pod directly.  This will work but will fail if the pod gets deleted and recreated with a new IP.
The only disadvantage of this PR's approach is that the `jq` package must be installed.  We could look at other one-liners to accomplish this without 3rd party packages but `jq` makes it pretty clean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/156)

Use heketi's service IP and port

---

deploy/ocp-templates/heketi-template.yaml

Fixes issue #162: Invalid DeploymentConfig on OpenShift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/165)

Fixed issue #162: Invalid DeploymentConfig on OpenShift

---

deploy/gk-deploy

Use terminal escape commands to improve logging. These changes allow check_pods() to not spam the terminal when using `-v` while also translating the output to something legible in the log file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/152)

Better logging

---

deploy/gk-deploy

The assumption is that in a OpenShift environment, users want
to use oc. They can still force the use of kubectl with the --cli
switch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/170)

gk-deploy: default to 'oc' as cli if found.

---

deploy/kube-templates/heketi-deployment.yaml

The deployer fails to deploy because on yaml alignment issue:
```
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ... OK
error: error validating "./kube-templates/heketi-deployment.yaml": error validating data: [found invalid field data for v1.ObjectMeta, found invalid field type for v1.ObjectMeta]; if you choose to ignore these errors, turn validation off with --validate=false
Waiting for heketi pod to start ... Timed out waiting for pods matching 'glusterfs=heketi-pod'.
the server doesn't have a resource type "dc"
serviceaccount "heketi-service-account" deleted
Error from server (NotFound): secrets "heketi-db-backup" not found
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix yaml alignment issue

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

Bind mount the /etc/ssl of host to container which can be used for encryption of gluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/176)

Add encryption support to gluster containers

---

deploy/gk-deploy

A modification to  #178 that allows for subcommand output to be sent to stdout (and the log file) in real time. This also allows the capture of any return codes from the subcommands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/182)

Properly capture subcommand output in both stdout and log file

---

deploy/gk-deploy

Implement and check a return code from check_pods(). Also allow a custom wait timer for a given check_pods() call.
These two commits are in the same PR because they both rely on the revert in the first commit. These are an alternative implementation to #175 due to some issues encountered in testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/181)

check_pods() return code

---

deploy/kube-templates/glusterfs-daemonset.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/177)

cgroup should be mounted as readonly

---

deploy/gk-deploy
deploy/kube-templates/heketi-deployment.yaml
deploy/ocp-templates/heketi-template.yaml

Cleanup the labels given to our Kubernetes/OpenShift resources, and make sure we only delete the resources we intend to delete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/154)

Label cleanup

---

deploy/gk-deploy

Allow the script to detect if a device or node has failed to load
from the topology file and alert the user on what to do. This is
fixing a regression introduced by PR #182.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/183)

Fix regression in topology load error reporting

---

deploy/gk-deploy
deploy/kube-templates/deploy-heketi-deployment.yaml
deploy/ocp-templates/deploy-heketi-template.yaml

Heketi upstream has now disabled the backup of its
DB to kubernetes secret by default (due to the size
limit).
This reverts commit 82c35a55686636632198a12b4016ee714cf8966f.
("Support for heketi 4 Release changes")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/200)

Resurrect the deploy-heketi deployment scheme.

---

.travis.yml
Makefile
tests/Makefile
tests/README.md
tests/common/subunit.sh
tests/gk-deploy/run.sh
tests/gk-deploy/stubs/kubectl
tests/gk-deploy/stubs/oc
tests/gk-deploy/stubs/oc-context.txt
tests/gk-deploy/test_gk_deploy_basic.sh
tests/run.sh
tests/yaml/glusterfs-daemonset-wrong.yaml
tests/yaml/run.sh
tests/yaml/test_syntax.sh

This is based on the original ideas of @MohamedAshiqrh 's PR #184 .
I basically took (and slightly) extended the kinds of commands that are run,
but put it into more of a test framework. (Copied the tiny "subunit.sh" from samba).
So now it really fails when a test fails. Also integrated this into "make test" and into .travis.yml.
I am pushing this to get some comments.
It currently contains the patches of PR #193 as well.
If we agree that this is the way to go, and if we merge #193, then I'd rebase once more to make git log clean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/194)

Add an initial testsuite

---

deploy/gk-deploy

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/222)

oc process: -v is deprecated, use -p instead

---

vagrant/roles/master/tasks/main.yml

this adapts for the change of:
https://github.com/kubernetes/kubernetes/pull/41820
renamed --use-kubernetes-version to --kubernetes-version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/226)

vagrant: fix kubeadm init call

---

vagrant/roles/common/tasks/main.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/224)

vagrant: give firewalld rules names for easier stepping/tracking

---

deploy/gk-deploy

gk-deploy does not setup heketi with db backed up to secrets, hence it
is not right that we delete the secrets for the same.
Closes: #231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/232)

don't delete a secret that we don't create

---

deploy/gk-deploy

PR #230 took away the ability to run gk-deploy outside the cluster for OpenShift deployments by removing the ability to use a route when determining the heketi URL. This PR re-establishes that, fixes #229, and introduces better debug output and a wait timer to the operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/233)

Properly wait for heketi URL

---

deploy/gk-deploy

This is needed as of kubernetes 1.6 which defaults to RBAC
authorization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/236)

gk-deploy: allow the heketi-service-account to view kubernetes info

---

deploy/gk-deploy

The latest version of Openshift (3.5 / origin 1.5)
depreated -v 'value' in favor of  -p value in the 'oc process'
command. gk-deploy was recently changed to work with 3.5/1.5.
This patch enables gk-deploy's backward compatibility with
older versions based on the oc version.
Pair-Programmed-With: Michael Adam <obnox@redhat.com>
Signed-off-by: hchiramm <hchiramm@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/244)

make gk-deploy run with openshift 3.4 (origin 1.4) again

---

deploy/gk-deploy

The second argument of check_pods() can either be a timeout integer
value or a string to check for the status field. In the case of
a status string, it was mistakenly used as an override for the
timeout, leading to always error with timeout.
This patch lets check_pods inspect the second argument and only
use it as a timout override if it is numeric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/245)

gk-deploy: fix error in check_pods() when second argument is a string

---

.travis.yml
tests/README.md
tests/complex/README.md
tests/complex/lib.sh
tests/complex/run.sh
tests/complex/test-dynamic-provisioning.sh
tests/complex/test-gk-deploy.sh
tests/complex/test-inside-dynamic-provisioning.sh
tests/complex/test-inside-gk-deploy.sh
tests/complex/test-setup.sh
tests/complex/test-teardown.sh
tests/simple/gk-deploy/run.sh
tests/simple/gk-deploy/stubs/kubectl
tests/simple/gk-deploy/stubs/oc
tests/simple/gk-deploy/test_gk_deploy_basic.sh
tests/simple/run.sh
tests/simple/yaml/run.sh
tests/simple/yaml/test_syntax.sh

These functional tests basically run the steps of the
quickstart guide and the dynamic provisioning example.
./run.sh will bring up vagrant, run all tests and will
destroy the vagrant environment again.
Tests can also be run individually against an already
running vagrant environment:
./test-gk-deploy.sh
./test-dynamic-provisioning.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/225)

test: add first functional tests

---

deploy/gk-deploy

context-name != current namespace for kubectl as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/264)

should use namespace instead of context-name

---

vagrant/roles/common/tasks/main.yml

The yum URL now redirects to a different place, let us change to that.
Also, the packages might not be signed always, removing gpg check there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/270)

update yum repo url and disable gpg check

---

deploy/gk-deploy
deploy/heketi.json.template
deploy/kube-templates/deploy-heketi-deployment.yaml
deploy/kube-templates/heketi-deployment.yaml
deploy/ocp-templates/deploy-heketi-template.yaml
deploy/ocp-templates/heketi-template.yaml

This PR intends to allow gk-deploy to deploy a solution where heketi remains containerized and manages a set of non-containerized GlusterFS nodes. In its most basic form, this new functionality can be achieved by running:
```
gk-deploy -s <keyfile>
```
Where `<keyfile>` is a path to an SSH private key that can be used to get acces to either root or a sudoable account on the GlusterFS nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/281)

Use containerized heketi with non-containerized GlusterFS nodes

---

deploy/gk-deploy
deploy/kube-templates/deploy-heketi-deployment.yaml
deploy/kube-templates/glusterfs-daemonset.yaml
deploy/kube-templates/heketi-deployment.yaml
deploy/kube-templates/heketi-service-account.yaml
deploy/ocp-templates/deploy-heketi-template.yaml
deploy/ocp-templates/glusterfs-template.yaml
deploy/ocp-templates/heketi-service-account.yaml
deploy/ocp-templates/heketi-template.yaml
docs/setup-guide.md
vagrant/roles/master/tasks/main.yml
vagrant/roles/nodes/tasks/main.yml

This PR allows for gk-deploy to be rerun in the same environment and continue from where it determines to be where it left off. It also removes the default behavior to abort on error, allowing for faster troubleshooting of a failed environment and introducing the ability to manually fix it before rerunning the script to continue. This also removes the need for the `--load` parameter. Finally, I removed the requirement of having `heketi-cli` installed, opting to use the one in the heketi pods instead.
Note that this does not resolve the problem that we have where we can not recover from an inconsistent or corrupt heketi database. If this happens after the topology has been loaded, the user has no recourse but to run `-g --abort` and wipe the GlusterFS storage.
This PR also includes a few …

Introduce idempotent execution in gk-deploy

---

deploy/gk-deploy

regression introduced by the patch to make
gk-deploy runnable everywhere...
Can't use realpath in the travis CI test env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/317)

gk-deploy: fix failure to run in testsuite

---

tests/complex/lib.sh
tests/complex/run.sh
tests/complex/test-dynamic-provisioning.sh
tests/complex/test-gk-deploy.sh
tests/complex/test-setup.sh
tests/complex/test-teardown.sh
tests/simple/common/shell_tests.sh
tests/simple/gk-deploy/run.sh
tests/simple/gk-deploy/test_gk_deploy_basic.sh
tests/simple/run.sh
tests/simple/shell/run.sh
tests/simple/shell/test_realpath.sh
tests/simple/yaml/run.sh
tests/simple/yaml/test_syntax.sh
vagrant/demo/demo-deploy.sh
vagrant/demo/demo-dynamic-provisioning.sh
vagrant/demo/demo-inside-wrapper.sh
vagrant/demo/demo-prepare.sh
vagrant/demo/demo-status.sh
vagrant/demo/demo-test-heketi.sh
vagrant/demo/util.sh

Realpath is not available in travis CI.
The bad thing is that these errors got unnoticed.
* So this removes the uses of realpath.
* And it adds a test to make sure that realpath is not used...
* Finally, (this could be put into a separate PR), this fixes the simple testsuite to do proper error propagation. (Previously, errors could go unnoticed even if the test itself detected it.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/319)

Fix selftests in CI by removing realpath

---

vagrant/rollback.sh

properly fall back if vagrant sandbox is not installed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/323)

Fix rollback

---

deploy/gk-deploy

If the image is more securely configured, heketi-cli doesn't have write
permissions to the root of the filesystem of the container. Changed the
output location to /tmp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/325)

gk-deploy: Change container directory of heketi-storage.json

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

A followup to #214, based on discussions therein. This configuration sets the GlusterFS pod to the "Burstable" QoS tier. More information [here](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/).
I am open to debate on more reasonable request values, as long as the memory request stays under `1Gi`. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/324)

gk-deploy: Set resource requests for GlusterFS pod

---

deploy/gk-deploy

If run not from terminal, kubectl shows this error:
Unable to use a TTY - input is not a terminal or the right kind of file
It makes the script think that topology loading failed and exit with
error:
Error loading the cluster topology.
That said we don't need to forward terminal here at all - we call CLI
that doesn't interact with terminal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/329)

Don't try to forward terminal to `kubectl exec` calls

---

deploy/gk-deploy

Due to issue in kubectl ( kubernetes/kubernetes#48924 ) it outputs some
warnings to stderr and they are considered to be output lines and it
breaks the script in 2 places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/330)

Don't add stderr to stdout when parsing `kubectl get pod` output

---

vagrant/README.md
vagrant/Vagrantfile
vagrant/gcr-proxy-state.sh
vagrant/gcr_proxy.yml
vagrant/global_vars.yml
vagrant/roles/common/templates/docker.j2
vagrant/roles/master/defaults/main.yml
vagrant/roles/master/tasks/gcr_proxy.yml
vagrant/roles/master/tasks/main.yml
vagrant/roles/master/templates/nginx.conf.j2
vagrant/roles/nodes/tasks/gcr_proxy.yml
vagrant/roles/nodes/tasks/main.yml

This introduces the ability to configure an nginx proxy that will
redirect traffic destined for gcr.io to a custom registry. This allows
the user to push copies of the container images from gcr.io to their
custom registry and then pull them in subsequent deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/311)

vagrant: Implement gcr.io proxy

---

vagrant/global_vars.yml

Have the commented out value match the ip address that we use
for the vagrant boxes, so that in case we use docker-registry-run.sh
to create the registry, we just need to comment out the line
to make use of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/336)

vagrant: make it a little more easy to use the created local registry

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

Added new env. variable GB_GLFS_LRU_COUNT for indicating maximum number
of block hosting volumes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/335)

Added new env. variable GB_GLFS_LRU_COUNT for indicating maximum number

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

Fix TCMU log directory name as TCMU_LOGDIR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/344)

Fix TCMU log directory name as TCMU_LOGDIR

---

tests/simple/gk-deploy/stubs/cli.sh

As per information provided in
https://github.com/koalaman/shellcheck/wiki/SC2199, we need to use $*
instead of ${@} in cli.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/352)

fix SC2199 in tests/simple/gk-deploy/stubs/cli.sh

---

deploy/gk-deploy
deploy/kube-templates/deploy-heketi-deployment.yaml
deploy/kube-templates/heketi-deployment.yaml
deploy/ocp-templates/deploy-heketi-template.yaml
deploy/ocp-templates/heketi-template.yaml

If ssh executor is used, it also generally means that Gluster is not
containerized. In such instances, we don't have the startup script in
Gluster container which would look at /var/lib/heketi/fstab for bricks.
Hence, this patch changes the HEKETI_FSTAB ENV to /etc/fstab when
sshexec is chosen.
For now, this is sufficient. When and if we want to support ssh access
to Gluster containers, we will have to provide a flag --fstab to let
users decide where the file should reside. Not now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/351)

when using ssh executor provide /etc/fstab as ENV

---

vagrant/README.md
vagrant/global_vars.yml

Without specifying the Kubernetes version the playbooks fail due to
behavior changes in kubeadm and friends.
Explicitly ask for 1.7.8 as that is the newest version of 1.7 in the
google yum repo.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/373)

vagrant: use kubernetes version 1.7.8

---

vagrant/global_vars.yml
vagrant/roles/common/files/10-kubeadm-post-1.8.conf
vagrant/roles/common/tasks/main.yml
vagrant/roles/master/tasks/main.yml
vagrant/roles/nodes/tasks/main.yml

Conditionalize various aspects of the ansible scripts in order to
support alternative Kubernetes versions. One can edit the
global_vars.yml and provide a value to "kubernetes_version" of either
"latest" or a version number such as "1.8.1", "1.7.8", etc.
Tested specifying: latest, 1.8.1, 1.7.8, 1.7.1, 1.6.11
Signed-off-by: John Mulligan <jmulligan@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/376)

vagrant: conditionalize ansible scripts to support alt. k8s versions

---

README.md

The quickstart guide is nice and straightforward but I didn't intially
realize caching was possible. This change adds a note in the quickstart
to indicate to readers that caching is possible and that one should
refer to the vagrant directory readme for that information.
I was a tad bit iffy on where to put the note so I'm willing to move
it to later in the quickstart if we think it interrupts the flow
of the text.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/379)

vagrant: add note to the main readme to indicate caching is possible

---

vagrant/README.md
vagrant/Vagrantfile
vagrant/global_vars.yml
vagrant/roles/common/tasks/main.yml

* Adds a top level variable for vm disk caching types.
* Adds custom yum repos support for cross vm rpm caching
* Adds helper variable for /etc/hosts
Using the pulp system for caching rpms and docker images I observed some minor speedups of rpm and the gluster and heketi docker image install steps.
Friday 27 October 2017  13:39:18 -0400 (0:00:00.011)       0:06:46.133
===============================================================================
common : install base packages ---------------------------------------- 115.18s
nodes : Pull GlusterFS Docker image ------------------------------------ 65.86s
master : wait for dns to be ready -------------------------------------- 46.47s
nodes : Pull heketi Docker image --------------------------------------- 42.65s
master : kubeadm init …

Add additional support for caching in vagrant dir

---

deploy/gk-deploy

in my cluster settings, where `istio-initializer` https://istio.io/` is enabled, which will auto inject `istio-proxy` container into any pod in kubernetes. So the right condition  should be '2/2'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/389)

fix pods ready condition

---

docs/setup-guide.md

See issue #392.
By default on Ubuntu 16.04 version of glusterfs-client do not match version of server which causes client crash on mount attempt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/409)

Added version matching requirement to docs

---

vagrant/roles/master/tasks/main.yml

This fixes an issue I was hitting with mutltiple runs. Usually the
first run of the playbooks would work fine but if a different issue
was hit and I neded to re-run them I kept hitting errors on
the weave step related to connection failures. This change adds a
wait for the port to be available before running that troublesome
step.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/416)

wait for kubernetes before trying to deploy weave

---

deploy/gk-deploy

The new --developer option configures the "heketidbstorage" volume with
a durability=none configuration. This makes it possible to run Heketi
with a single Gluster pod. Obviously this is not suitable for
deployments that are not used for basic testing or developing.
Requires: heketi/heketi#966
Signed-off-by: Niels de Vos <ndevos@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/422)

gk-deploy: add --developer option

---

vagrant/roles/master/tasks/main.yml

While deploying the Vagrant environment, Kubernetes 1.9.2 is currently
used. This version does not seem to be compatible with the 1.6 version
of Weave Net. While the weave- pods are starting, the following errors
are reported:
dockerd-current[6461]: ERROR: logging before flag.Parse: E0119 15:50:15.165210    9894 reflector.go:205] github.com/weaveworks/weave/prog/weave-npc/main.go:230: Failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:kube-system:weave-net" cannot list networkpolicies.networking.k8s.io at the cluster scope
By using the recommended way to install the add-on, a matching version
will automatically be picked.
URL: https://www.weave.works/docs/net/latest/kubernetes/kube-addon/
Suggested-by: John Mulligan …

vagrant: use a matching version of Weave Net

---

deploy/gk-deploy

Currently there is no Heketi release available that supports the
--durability option for the 'heketi-cli setup-openshift-heketi-storage'
command. In order to give the users a meaningful error message, add a
check to see if the --durability=none option is accepted. This is done
in combination with the --help option, which will just exit successfully
in case the options are valid, or exit with an error otherwise.
Signed-off-by: Niels de Vos <ndevos@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/427)

gk-deploy: check if heketi in the pod can support the --single-node option

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

It is possible that lvm takes more time to bring up the brick devices
if there are many number of bricks. Increase the threshold to account
for the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/431)

increase failure threshold for glusterfs pods

---

deploy/gk-deploy

Heketi service is created in k8s with ClusterIP type so it is not available from the outside unless we're using a proxy. Instead of that we run the `curl` command probe from a pod in the `deploy-heketi` deployment
Fixes https://github.com/gluster/gluster-kubernetes/issues/412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/414)

Probe heketi service from deploy-heketi pod in k8s

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

If the probe script does not exist the statement falls back to the
previous method of checking only the status of glusterd.
This should only be merged if https://github.com/gluster/gluster-containers/pull/105 is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/523)

[RFC] deploy: if available, use new probe script in the glusterfs container image

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

It seems recent versions of CRI-O cause problems when bind-mounting /dev
into a privileged container. When a container is privileged, it
automatically gets access to /dev, a bind-mount is setup by the runtime.
With the new CRI-O versions, the following error is reported and the
containers fail to start:
Warning  Unhealthy  1m (x346 over 1h)  kubelet, cnv-executor-lbednar-node2.example.com  (combined from similar events): Liveness probe errored: rpc error: code = Unknown desc = command error: time="2018-11-15T14:27:20Z" level=error msg="open /dev/null: permission denied
"
open /dev/null: permission denied
exec failed: container_linux.go:336: starting container process caused "read init-p: connection reset by peer"
, stdout: , stderr: , exit code -1
Fixes: …

deploy: no need to have volumes for /dev in privileged containers

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

Commit 2f1114a removed the bind-mount for /dev as this will be setup by
the container runtime automatically. However it seems that /dev/disk is
missing, prevending users to supply /dev/disk/by-id/* device names to
Heketi.
This change adds /dev/disk as an additional bind-mount. CRI-O does
prevent /dev to be bind-mounted, but subdirectories of /dev do not seem
to be an issue.
Reported-by: Gal Ben Haim <gbenhaim@redhat.com>
Signed-off-by: Niels de Vos <ndevos@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/542)

deploy: bind-mount /dev/disk into the glusterfs-server container

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

Commit 2f1114a removed the bind-mount for /dev as this will be setup by
the container runtime automatically. However it seems that /dev/mapper
is missing, prevending users to supply /dev/mapper/* device names to
Heketi. It also seems possible that not all(?) LVM devices are available
when a container starts.
This change adds /dev/mapper as an additional bind-mount. CRI-O does
prevent /dev to be bind-mounted, but subdirectories of /dev do not seem
to be an issue.
Fixes: #499
Signed-off-by: Niels de Vos <ndevos@redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/544)

deploy: bind-mount /dev/mapper into the glusterfs-server container

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml
vagrant/Vagrantfile
vagrant/roles/master/tasks/main.yml

By not bind-mounting /dev in the container anymore, gluster-block fails to create block-volumes. Unfortunately bind-mounting /dev is not possible with CRI-O, so we came up with a different approach to reach the same goal.
The gluster/gluster-container#115 change introduces a feature in the early start script for the glusterfs-server container. It is now possible to `mount --rbind` an alternative /dev from the host onto the /dev path in the container.
It also has been noticed that CRI-O secures `/sys` more than Docker does. tcmu-runner (part of gluster-block) needs write access to `/sys/module` and `/sys/class`.
With these two changes, gluster-block functions again on recent versions of OpenShift, both with Docker and CRI-O runtimes.
---
This change is [<img …

gluster-block needs to dynamically create /dev/uio* devices

---

deploy/kube-templates/glusterfs-daemonset.yaml
deploy/ocp-templates/glusterfs-template.yaml

This patch fixes #539. Not all supported distros have /lib as a symlink of
/usr/lib. For example, Ubuntu 18.04 doesn't. This causes an issue with
tcmu-runner; which requires target_core_user and other modules to be able to
build.
In order to fix this, we just need to mount `/lib/modules` instead so all of
the supported distributions are capable of the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/557)

Correcting the modules path in order to support other distros

---

deploy/heketi.json.template

We don't want to deploy heketi with default secrets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gluster/gluster-kubernetes/602)

remove the default secrets from the json template
